### PR TITLE
Automatically add Crashlytics Input Files for the Run Script in Xcode 15

### PR DESCRIPTION
**Pull request by samedson**
### Description

 - Related to https://github.com/firebase/firebase-ios-sdk/issues/11400, Xcode 15 enforces tighter requirements on Input Files for Run Scripts. This automatically includes Crashlytics Input Files.
 - Confirmed the API we're using exists in Unity 2019.1: https://docs.unity3d.com/2019.1/Documentation/ScriptReference/iOS.Xcode.PBXProject.AddShellScriptBuildPhase.html

### Type of Change
Place an `x` the applicable box:
- [x] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

### CODE REVIEW

**Comment by pavm035** [comment]
Hi @samedson 

May I know when this fix will be released?

**Comment by pavm035** [comment]
@samedson  May i know when this fix will be released?

**Comment by samedson** [comment]
@pavm035 sorry I was OOO - we're going to target the next release which will be around the end of August

**Comment by samedson** [comment]
Finished validating this in a project
Screenshot 2023-08-22 at 3 43 53 PM

**Review by themiswang — APPROVED** [review]

**Pull request merged**
